name: Dev Server

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  run:
    name: Deploy with NPM
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /
    steps:
    - name: Install dependencies
      run: npm install
    - name: Run Server
      run: npm run dev
